name: AutoBuild

on: 
  milestone:
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: RunFile
      run: build.sh
      working-directory: ./
