name: AutoBuild

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: runBuild
      run: ./autoBuild.sh
      shell: bash
      with:
        password: ${{ secrets.ACCESS_TOKEN }}
