name: AutoBuild

on: 
  milestone:
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: buildCommand
      uses: buildtool/build-action@v1.1
      with:
        run: autoBuild.sh
