name: AutoBuild

on: 
  milestone:
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: buildtool/build-action@v1.1
    - name: runBuild
      run: autoBuild.sh
